# Generated by Django 2.2.5 on 2020-02-23 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_menudetail_menumaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='guest', max_length=30)),
                ('visitedDate', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='menumaster',
            name='customer',
            field=models.ForeignKey(default='defaultMenu', on_delete=django.db.models.deletion.CASCADE, to='posts.Customer'),
        ),
    ]
