# Generated by Django 2.2.5 on 2020-02-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200223_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank='true', default='guest', max_length=30, null='true'),
        ),
    ]
